sudo: required
language: java
jdk: oraclejdk8
before_install:
  - pip install --user codecov
after_success:
  - codecov
script:
- sh tron.sh
- ./gradlew lint
- ./gradlew test jacoco
addons:
  ssh_known_hosts:
  - 47.93.9.236:22008
skip_build:
- README.md
- LICENSE
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: develop
after_deploy:
  - ./gradlew stest
