version: 2
jobs:
  build:
    branches:
      only:
      - master
      - develop
      - addinCircleCI
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/java-tron
    steps:
    - checkout
    - run:
        name: Daily Build Report
        command: curl http://60.205.215.34/Daily_Build_Task_Report
    - run:
        name: Download Links
        command: |
          echo "Please visit following website to download java-tron.jar"
          echo "http://60.205.215.34/Daily_Build/java-tron.jar"

          echo "The following compressed package is provided for user to try"
          echo "http://60.205.215.34/Daily_Build/ava-tron.tar.gz"