version: 2
jobs:
  build:
    branches:
      only:
      - master
      - develop
      - addinCircleCI
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/java-tron
    steps:
    - checkout
    - test1:
        run:
          name: Daily Build Report
          command: curl http://60.205.215.34/Daily_Build_Task_Report


    - test2:
        run:
          requires:
            - test1
          name: Download Links
          command: |
            echo "Please visit following website to download java-tron.jar on browsers"
            echo "--- http://60.205.215.34/Daily_Build/java-tron.jar"
            echo "To view Daily Rplay and Stress Test logs please visit website below on browsers"
            echo "--- http://60.205.215.34/latestReplayLog"
            echo "--- http://60.205.215.34/latestStressLog"
            echo "The following compressed package is provided for user to set up Fullnode. Please use Linux OS to Download"
            echo "--- curl -# -O http://60.205.215.34/Daily_Build/java-tron.tar.gz"
            echo "To unzip file use the command below"
            echo "--- tar -xzvf java-tron.tar.gz"